In [1]:
liste = [1,1,2,3,4,5,1,2,1]
liste.count(1)

4

In [3]:
set1 = set([5,7,9])
set2 = set([5,6,7])
print(set1.difference(set2))

{9}


In [4]:
liste = ["a","b","c"]
liste.extend(liste)
liste

['a', 'b', 'c', 'a', 'b', 'c']

In [5]:
liste

['a', 'b', 'c', 'a', 'b', 'c']

In [6]:
liste.pop()

'c'

In [7]:
liste

['a', 'b', 'c', 'a', 'b']

In [8]:
liste.pop(1)

'b'

In [9]:
liste

['a', 'c', 'a', 'b']

In [10]:
set1 = set([5,7,9])
set2 = set([5,6,7])
set1.symmetric_difference(set2)


{6, 9}

In [11]:
set1 = set([5,7,9])
set2 = set([5,6,7])
set2.difference(set1)

{6}

In [12]:
liste = [10,10,20,40]
liste.clear()
liste

[]

In [14]:
set([1,3,6,19])

{1, 3, 6, 19}

In [15]:
liste = ["A","B","C"]

In [21]:
liste.insert(0,"D")

In [22]:
liste

['D', 'D', 'D', 'A', 'B', 'C']

In [1]:
def harf_say(x):
    return len(x)
 
harf_say("Merhaba!")

8

In [3]:
def harf_say(x):
    len(x)
 
harf_say("Merhaba!")

In [4]:
def mesaj():
    print("Merhaba!")    
    
mesaj()

Merhaba!


In [5]:
if [1,2,3,4][2] == 2:
    print("YES")
else:
    print("NO")   

NO


In [6]:
def yazdir(metin):
    print(metin, "yazanlar")
 
yazdir("gelecegi")

gelecegi yazanlar


In [7]:
a = [1,2,3]
b = []
for i in a:
    b.append(i**2)
b

[1, 4, 9]

In [8]:
def islem(x, y):
    print(x + y)
 
islem(1,9)

10


In [9]:
A = 12    
if type(A) == str:
    A = A.strip("*")
    print(A)    
else:
    A  = "*" + str(A) + "*"
    print(A.strip())

*12*


In [10]:
sayilar = [10,20,30]
 
for i in sayilar:
    if i > 20:
        print(i/2)

15.0


In [11]:
A = []

for i in [1,2,3,4]:
    A.append(i)

A[0]

1

In [12]:
for i in ["a",11]:
    print(i)

a
11


In [13]:
liste = ["a","b","c"]
liste.reverse()
print(liste)

['c', 'b', 'a']


In [14]:
A = "*A*"    
if type(A) == str:
    A = A.strip("*")
    print(A)

A


In [15]:
if [1,2,3,4][1] == 2:
    print("YES".lower())
else:
    print("NO")    

yes


In [16]:
A = []
for i in ["ali","veli","isik"]:
    A.append(i.replace("i","a"))
print(A)

['ala', 'vela', 'asak']


In [17]:
list(filter(lambda x: x < 2, [1,2,3,4,5]))


[1]

In [18]:
liste = ["a",20,10,30,"b"]
list(filter(lambda x: type(x) == int, liste))

[20, 10, 30]

In [19]:
from functools import reduce
reduce(lambda a,b: a+b, ["a","4","a"])

'a4a'

In [20]:
def yap(x,y,z):
    try:
        print(x/y*z)
    except ZeroDivisionError:
        print("gecersiz islem")

yap(1,2,0)

0.0


In [21]:
list(map(lambda x: x.upper(), ["Ali","Veli","isik"]))

['ALI', 'VELI', 'ISIK']

In [22]:
list(filter(lambda x: len(x) > 8, ["pazartesi","sali","carsamba","persembe","cuma"]))


['pazartesi']

In [23]:
list(map(lambda x: x*1, [2,7,4]))


[2, 7, 4]

In [24]:
A = [1,2,3,4,5]

if type(A) == ():
    print("islem gecersiz")
else:
    print(list(map(lambda x: x/1, A)))

[1.0, 2.0, 3.0, 4.0, 5.0]


In [25]:
from functools import reduce
A = ["Veri","Bilimi","Okulu"]
reduce(lambda a,b: a+b, list(map(lambda x: x[0], A)))

'VBO'

In [26]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2])

a+b

array([3, 3, 3])

In [27]:
from functools import reduce
reduce(lambda a,b: a/b, [8,4,2])

1.0

In [28]:
import numpy as np
5*np.array([1,2,3])

array([ 5, 10, 15])

In [30]:
a =   np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

a[3,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [31]:
v = np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])


[v[1], v[3]]

[3, 9]

In [33]:

import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
"merve".center(20,"*")

'*******merve********'

In [37]:
-90 to -100 (232324, %40)
-80 to -80 (2324, %4)

SyntaxError: invalid syntax (<ipython-input-37-2cfe00c26769>, line 1)

In [48]:
a = "-90 to -100"
b = "-80 to -80"
c = "(232324, %40)"
d = "(2324, %4)"
print(a.ljust(40-len(a)-len(c)," ") + c)
print(b.ljust(40-len(b)-len(d)-1," ") + d)

-90 to -100     (232324, %40)
-80 to -80         (2324, %4)


In [49]:
-90 to -100               (232324, %40)
-80 to -80                   (2324, %4)


SyntaxError: invalid syntax (<ipython-input-49-8dc2002cd986>, line 1)

In [50]:
df_num = df.select_dtypes(include = ["float64", "int64"])


NameError: name 'df' is not defined

In [52]:
import seaborn as sns
df = sns.load_dataset("tips")

In [53]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [54]:
df_num = df.select_dtypes(include = ["float64", "int64"])


In [55]:
df_num

total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
239       29.03  5.92     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[244 rows x 3 columns]

In [56]:
import seaborn as sns
diamonds = sns.load_dataset('diamonds')

In [57]:
diamonds

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [63]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [67]:

kat_df = df.select_dtypes(include = "o")

kat_df

TypeError: data type 'o' not understood

In [68]:
import pandas as pd
df.column = pd.Categorical(df.method)

AttributeError: 'DataFrame' object has no attribute 'method'

In [77]:

df["sex"].value_counts().count()

2

In [76]:
df.sex.count();

In [80]:
df["total_bill"].value_counts()

13.42    3
10.33    2
20.29    2
18.29    2
17.92    2
        ..
30.40    1
26.59    1
19.65    1
9.55     1
5.75     1
Name: total_bill, Length: 229, dtype: int64

In [88]:
import pandas as pd
df = pd.DataFrame({"sem":["1"], "mer":["2"]})
df

sem mer
0   1   2

In [89]:
pd.read_txt("reading_data/duz_metin.txt")



AttributeError: module 'pandas' has no attribute 'read_txt'

In [90]:
df

sem mer
0   1   2

In [92]:
df["0"]

KeyError: '0'

In [96]:
df.values

array([['1', '2']], dtype=object)

In [97]:
x = pd.Series([1,2,3])

In [98]:
x

0    1
1    2
2    3
dtype: int64

In [99]:
x.dtype


dtype('int64')

In [100]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [102]:
df

var1  var2  var3
0    15     6    19
1    25    23    15
2    10    10     3
3    27     3    15
4    26    29    28
5    10    28     2
6    28    26    18
7     4     5     3
8    15    23     4
9    15    24    18

In [103]:
seri = pd.Series([121,200,150,99])

seri.values

array([121, 200, 150,  99])

In [104]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})



KeyError: 'gruplar'

In [113]:
import numpy as np
m = np.random.randint(9, size=9)

In [115]:
m = m.reshape((3,3))
m

array([[2, 4, 6],
       [2, 1, 5],
       [8, 6, 4]])

In [140]:
m[m<5]

array([2, 4, 2, 1, 4])

In [145]:
m[m<5][1:3]

array([4, 2])

In [135]:
m[m<5]

array([2, 4, 2, 1, 4])

In [139]:
np.where(m < 5, m, 0)

array([[2, 4, 0],
       [2, 1, 0],
       [0, 0, 4]])

In [1]:
!pip install researchpy
import researchpy as rp

In [3]:
import seaborn as sns
df = sns.load_dataset('tips')

In [4]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
rp.summary_cat(df[["sex","smoker","day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [7]:
rp.summary_cont(df[["total_bill","tip","size"]])

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [11]:
rp.summer(df[["total_bill","tip","size"]])
rp.summer(df[["sex","smoker","day"]])

AttributeError: module 'researchpy' has no attribute 'summer'

In [14]:
import numpy as np
np.random.randint(140, 220, 1000)

array([215, 164, 216, 144, 154, 177, 178, 169, 149, 161, 197, 205, 161,
       194, 201, 211, 177, 161, 151, 180, 187, 146, 217, 153, 177, 142,
       183, 178, 161, 150, 166, 204, 215, 159, 166, 196, 169, 172, 165,
       160, 207, 196, 201, 214, 175, 186, 213, 160, 162, 143, 206, 163,
       180, 197, 141, 209, 167, 166, 147, 208, 198, 168, 196, 171, 160,
       177, 146, 210, 201, 217, 184, 142, 210, 169, 162, 155, 168, 147,
       187, 190, 150, 152, 148, 172, 186, 210, 178, 219, 163, 141, 162,
       159, 218, 217, 205, 172, 195, 212, 173, 169, 142, 172, 151, 170,
       148, 155, 173, 212, 140, 190, 196, 173, 150, 158, 178, 207, 179,
       202, 150, 181, 147, 140, 205, 163, 150, 211, 174, 142, 157, 210,
       140, 169, 199, 197, 197, 198, 148, 203, 151, 170, 148, 213, 150,
       173, 156, 197, 192, 183, 146, 211, 193, 176, 196, 178, 188, 173,
       149, 150, 142, 158, 145, 204, 153, 148, 145, 211, 170, 159, 185,
       203, 178, 172, 142, 203, 208, 147, 148, 151, 163, 140, 16

In [15]:
from scipy.stats import binom



In [16]:
binom

In [19]:
list(enumerate(df.columns))

[(0, 'total_bill'),
 (1, 'tip'),
 (2, 'sex'),
 (3, 'smoker'),
 (4, 'day'),
 (5, 'time'),
 (6, 'size')]

In [31]:
df['sex'].unique()

['Female', 'Male']
Categories (2, object): ['Female', 'Male']

In [35]:
df['sex'] = df['sex'].map({'Male':"Erkek", 'Female':'Kadin'})

In [36]:
df

total_bill   tip    sex smoker   day    time  size
0         16.99  1.01  Kadin     No   Sun  Dinner     2
1         10.34  1.66  Erkek     No   Sun  Dinner     3
2         21.01  3.50  Erkek     No   Sun  Dinner     3
3         23.68  3.31  Erkek     No   Sun  Dinner     2
4         24.59  3.61  Kadin     No   Sun  Dinner     4
..          ...   ...    ...    ...   ...     ...   ...
239       29.03  5.92  Erkek     No   Sat  Dinner     3
240       27.18  2.00  Kadin    Yes   Sat  Dinner     2
241       22.67  2.00  Erkek    Yes   Sat  Dinner     2
242       17.82  1.75  Erkek     No   Sat  Dinner     2
243       18.78  3.00  Kadin     No  Thur  Dinner     2

[244 rows x 7 columns]

In [8]:
import seaborn as sns
dia = sns.load_dataset('diamonds')

In [9]:
df = dia.copy()

In [52]:
[col for col in df.columns if df[col].dtype =='category']

TypeError: data type 'category' not understood

In [4]:
df

NameError: name 'df' is not defined

In [1]:
for index, row in df.iterrows():
    #print(index , row)

SyntaxError: unexpected EOF while parsing (<ipython-input-1-3a701e9a7cca>, line 2)

In [11]:
df['cut']

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...    
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: category
Categories (5, object): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']

In [ ]:
df['ccc'] = df.

In [22]:
for col in df.columns:
    if df[col].dtype == 'O':
    #if df[col].dtype:
        print(df[col].dtype)

In [26]:
df['cut'].str.lower()

0            ideal
1          premium
2             good
3          premium
4             good
           ...    
53935        ideal
53936         good
53937    very good
53938      premium
53939        ideal
Name: cut, Length: 53940, dtype: object

In [28]:
tips = sns.load_dataset('tips')
df = tips.copy()

In [31]:
df.groupby('day')['total_bill'].sum()

day
Thur    1096.33
Fri      325.88
Sat     1778.40
Sun     1627.16
Name: total_bill, dtype: float64

In [ ]:
df['day'].apply(lambda x : df['total_bill'].x )

In [32]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
df['diff'].dt.total_seconds()

In [34]:
import pandas as pd

In [36]:
df = pd.read_excel('MarketSales.xlsx',nrows=70,engine='openpyxl')

In [37]:
df.head()

ID  ITEMCODE                         ITEMNAME  FICHENO      DATE_  \
0  11738    5863.0  SPRITE 1 LT LIMON AROMALI GAZOZ    18456 2017-01-07   
1  10537       8.0                        TOZ SEKER    18105 2017-01-06   
2  11335    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
3  11336    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
4  10115   12808.0            FALIM SAKIZ 5LI CILEK    18005 2017-01-05   

   AMOUNT  PRICE  LINENETTOTAL  LINENET  BRANCHNR  ... CLIENTCODE  \
0     1.0   2.00          2.00     1.85        52  ...   467369.0   
1     5.0   2.65         13.25    12.27         8  ...   131464.0   
2     1.0   0.40          0.40     0.37        40  ...   656969.0   
3     1.0   0.40          0.40     0.37        40  ...   656969.0   
4     1.0   0.40          0.40     0.37        41  ...   447336.0   

       CLIENTNAME BRANDCODE   BRAND  CATEGORY_NAME1   CATEGORY_NAME2  \
0  Sercan KIZILOK       156  SPRİTE          İÇECEK     GAZLI İÇECEK   
1    İsmet ŞINGIR       NaN     NaN          İÇECEK        ÇAY KAHVE   
2     Yağız KUBAL       300   FALIM            GIDA  SAKIZ SEKERLEME   
3     Yağız KUBAL       300   FALIM            GIDA  SAKIZ SEKERLEME   
4    Habibe AYSAN       300   FALIM            GIDA  SAKIZ SEKERLEME   

       CATEGORY_NAME3           STARTDATE             ENDDATE GENDER  
0               GAZOZ 2017-01-08 16:16:11 2017-01-08 16:17:13      E  
1  SEKER TATLANDIRICI 2017-01-07 11:04:34 2017-01-07 11:05:37      E  
2               SAKIZ 2017-01-04 14:00:03 2017-01-04 14:01:01      E  
3               SAKIZ 2017-01-04 14:00:03 2017-01-04 14:01:01      E  
4               SAKIZ 2017-01-06 14:00:30 2017-01-06 14:01:03      K  

[5 rows x 26 columns]

In [38]:
df["time_dif"] =  df['ENDDATE'] - df['STARTDATE']
df.head()

ID  ITEMCODE                         ITEMNAME  FICHENO      DATE_  \
0  11738    5863.0  SPRITE 1 LT LIMON AROMALI GAZOZ    18456 2017-01-07   
1  10537       8.0                        TOZ SEKER    18105 2017-01-06   
2  11335    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
3  11336    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
4  10115   12808.0            FALIM SAKIZ 5LI CILEK    18005 2017-01-05   

   AMOUNT  PRICE  LINENETTOTAL  LINENET  BRANCHNR  ...      CLIENTNAME  \
0     1.0   2.00          2.00     1.85        52  ...  Sercan KIZILOK   
1     5.0   2.65         13.25    12.27         8  ...    İsmet ŞINGIR   
2     1.0   0.40          0.40     0.37        40  ...     Yağız KUBAL   
3     1.0   0.40          0.40     0.37        40  ...     Yağız KUBAL   
4     1.0   0.40          0.40     0.37        41  ...    Habibe AYSAN   

  BRANDCODE   BRAND CATEGORY_NAME1   CATEGORY_NAME2      CATEGORY_NAME3  \
0       156  SPRİTE         İÇECEK     GAZLI İÇECEK               GAZOZ   
1       NaN     NaN         İÇECEK        ÇAY KAHVE  SEKER TATLANDIRICI   
2       300   FALIM           GIDA  SAKIZ SEKERLEME               SAKIZ   
3       300   FALIM           GIDA  SAKIZ SEKERLEME               SAKIZ   
4       300   FALIM           GIDA  SAKIZ SEKERLEME               SAKIZ   

            STARTDATE             ENDDATE GENDER        time_dif  
0 2017-01-08 16:16:11 2017-01-08 16:17:13      E 0 days 00:01:02  
1 2017-01-07 11:04:34 2017-01-07 11:05:37      E 0 days 00:01:03  
2 2017-01-04 14:00:03 2017-01-04 14:01:01      E 0 days 00:00:58  
3 2017-01-04 14:00:03 2017-01-04 14:01:01      E 0 days 00:00:58  
4 2017-01-06 14:00:30 2017-01-06 14:01:03      K 0 days 00:00:33  

[5 rows x 27 columns]

In [39]:
df['sec'] = df['time_dif'].dt.total_seconds()

In [41]:
df['sec'].sort_values(ascending= False)

27    209.0
26    209.0
25    209.0
45    201.0
65    152.0
      ...  
43     11.0
52      9.0
69      8.0
11      5.0
18      5.0
Name: sec, Length: 70, dtype: float64

In [46]:
df['day_name'] = df['DATE_'].dt.day_name()
df.head()

In [47]:
df.head()

ID  ITEMCODE                         ITEMNAME  FICHENO      DATE_  \
0  11738    5863.0  SPRITE 1 LT LIMON AROMALI GAZOZ    18456 2017-01-07   
1  10537       8.0                        TOZ SEKER    18105 2017-01-06   
2  11335    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
3  11336    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
4  10115   12808.0            FALIM SAKIZ 5LI CILEK    18005 2017-01-05   

   AMOUNT  PRICE  LINENETTOTAL  LINENET  BRANCHNR  ...   BRAND CATEGORY_NAME1  \
0     1.0   2.00          2.00     1.85        52  ...  SPRİTE         İÇECEK   
1     5.0   2.65         13.25    12.27         8  ...     NaN         İÇECEK   
2     1.0   0.40          0.40     0.37        40  ...   FALIM           GIDA   
3     1.0   0.40          0.40     0.37        40  ...   FALIM           GIDA   
4     1.0   0.40          0.40     0.37        41  ...   FALIM           GIDA   

    CATEGORY_NAME2      CATEGORY_NAME3           STARTDATE  \
0     GAZLI İÇECEK               GAZOZ 2017-01-08 16:16:11   
1        ÇAY KAHVE  SEKER TATLANDIRICI 2017-01-07 11:04:34   
2  SAKIZ SEKERLEME               SAKIZ 2017-01-04 14:00:03   
3  SAKIZ SEKERLEME               SAKIZ 2017-01-04 14:00:03   
4  SAKIZ SEKERLEME               SAKIZ 2017-01-06 14:00:30   

              ENDDATE  GENDER        time_dif   sec      daye  
0 2017-01-08 16:17:13       E 0 days 00:01:02  62.0  Saturday  
1 2017-01-07 11:05:37       E 0 days 00:01:03  63.0    Friday  
2 2017-01-04 14:01:01       E 0 days 00:00:58  58.0   Tuesday  
3 2017-01-04 14:01:01       E 0 days 00:00:58  58.0   Tuesday  
4 2017-01-06 14:01:03       K 0 days 00:00:33  33.0  Thursday  

[5 rows x 29 columns]

In [48]:
df.head()

ID  ITEMCODE                         ITEMNAME  FICHENO      DATE_  \
0  11738    5863.0  SPRITE 1 LT LIMON AROMALI GAZOZ    18456 2017-01-07   
1  10537       8.0                        TOZ SEKER    18105 2017-01-06   
2  11335    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
3  11336    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
4  10115   12808.0            FALIM SAKIZ 5LI CILEK    18005 2017-01-05   

   AMOUNT  PRICE  LINENETTOTAL  LINENET  BRANCHNR  ... CATEGORY_NAME1  \
0     1.0   2.00          2.00     1.85        52  ...         İÇECEK   
1     5.0   2.65         13.25    12.27         8  ...         İÇECEK   
2     1.0   0.40          0.40     0.37        40  ...           GIDA   
3     1.0   0.40          0.40     0.37        40  ...           GIDA   
4     1.0   0.40          0.40     0.37        41  ...           GIDA   

    CATEGORY_NAME2      CATEGORY_NAME3           STARTDATE  \
0     GAZLI İÇECEK               GAZOZ 2017-01-08 16:16:11   
1        ÇAY KAHVE  SEKER TATLANDIRICI 2017-01-07 11:04:34   
2  SAKIZ SEKERLEME               SAKIZ 2017-01-04 14:00:03   
3  SAKIZ SEKERLEME               SAKIZ 2017-01-04 14:00:03   
4  SAKIZ SEKERLEME               SAKIZ 2017-01-06 14:00:30   

              ENDDATE  GENDER        time_dif   sec      daye month_day  
0 2017-01-08 16:17:13       E 0 days 00:01:02  62.0  Saturday         7  
1 2017-01-07 11:05:37       E 0 days 00:01:03  63.0    Friday         6  
2 2017-01-04 14:01:01       E 0 days 00:00:58  58.0   Tuesday         3  
3 2017-01-04 14:01:01       E 0 days 00:00:58  58.0   Tuesday         3  
4 2017-01-06 14:01:03       K 0 days 00:00:33  33.0  Thursday         5  

[5 rows x 30 columns]

In [49]:
df['month_day'].value_counts()

5    33
6    26
3     7
7     2
2     2
Name: month_day, dtype: int64

In [50]:
df

ID  ITEMCODE                         ITEMNAME  FICHENO      DATE_  \
0   11738    5863.0  SPRITE 1 LT LIMON AROMALI GAZOZ    18456 2017-01-07   
1   10537       8.0                        TOZ SEKER    18105 2017-01-06   
2   11335    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
3   11336    5979.0             FALIM SAKIZ 5LI NANE    18350 2017-01-03   
4   10115   12808.0            FALIM SAKIZ 5LI CILEK    18005 2017-01-05   
..    ...       ...                              ...      ...        ...   
65   3269    3197.0         F NEFFIS BUGDAY UNU 5 KG    16531 2017-01-05   
66   9643     368.0          CAYKUR FILIZ CAY 500 GR    17871 2017-01-06   
67   9809     267.0        CAYKUR TIRYAKI CAY 500 GR    17921 2017-01-06   
68   9614    2577.0                COFFEE MATE 50 GR    17861 2017-01-06   
69    918    2124.0              TEKEL 2001 KISA BOX    15848 2017-01-03   

    AMOUNT  PRICE  LINENETTOTAL  LINENET  BRANCHNR  ... CATEGORY_NAME1  \
0      1.0   2.00          2.00     1.85        52  ...         İÇECEK   
1      5.0   2.65         13.25    12.27         8  ...         İÇECEK   
2      1.0   0.40          0.40     0.37        40  ...           GIDA   
3      1.0   0.40          0.40     0.37        40  ...           GIDA   
4      1.0   0.40          0.40     0.37        41  ...           GIDA   
..     ...    ...           ...      ...       ...  ...            ...   
65     1.0   6.50          6.50     6.44        21  ...           GIDA   
66     1.0   8.25          8.25     7.65         7  ...         İÇECEK   
67     1.0   7.15          7.15     6.62        62  ...         İÇECEK   
68     1.0   0.95          0.95     0.88        52  ...         İÇECEK   
69     1.0   5.00          5.00     5.00        42  ...         SİGARA   

     CATEGORY_NAME2      CATEGORY_NAME3           STARTDATE  \
0      GAZLI İÇECEK               GAZOZ 2017-01-08 16:16:11   
1         ÇAY KAHVE  SEKER TATLANDIRICI 2017-01-07 11:04:34   
2   SAKIZ SEKERLEME               SAKIZ 2017-01-04 14:00:03   
3   SAKIZ SEKERLEME               SAKIZ 2017-01-04 14:00:03   
4   SAKIZ SEKERLEME               SAKIZ 2017-01-06 14:00:30   
..              ...                 ...                 ...   
65    UNLU MAMÜLLER                  UN 2017-01-06 19:20:36   
66        ÇAY KAHVE                 ÇAY 2017-01-07 12:08:19   
67        ÇAY KAHVE                 ÇAY 2017-01-07 16:12:21   
68        ÇAY KAHVE       SÜTTOZU KREMA 2017-01-07 11:04:07   
69              NaN                 NaN 2017-01-04 09:58:17   

               ENDDATE  GENDER        time_dif    sec      daye month_day  
0  2017-01-08 16:17:13       E 0 days 00:01:02   62.0  Saturday         7  
1  2017-01-07 11:05:37       E 0 days 00:01:03   63.0    Friday         6  
2  2017-01-04 14:01:01       E 0 days 00:00:58   58.0   Tuesday         3  
3  2017-01-04 14:01:01       E 0 days 00:00:58   58.0   Tuesday         3  
4  2017-01-06 14:01:03       K 0 days 00:00:33   33.0  Thursday         5  
..                 ...     ...             ...    ...       ...       ...  
65 2017-01-06 19:23:08       E 0 days 00:02:32  152.0  Thursday         5  
66 2017-01-07 12:08:42       K 0 days 00:00:23   23.0    Friday         6  
67 2017-01-07 16:13:34       K 0 days 00:01:13   73.0    Friday         6  
68 2017-01-07 11:04:26       E 0 days 00:00:19   19.0    Friday         6  
69 2017-01-04 09:58:25       K 0 days 00:00:08    8.0   Tuesday         3  

[70 rows x 30 columns]